### ISSUE TITLE
pretrained model has low mAP

### ISSUE THREAD

**Issue by TianyuLee** [yytzsy/SCDM#2]

**Comment by TianyuLee** [comment]
Hi Yitian, the pre-trained models in the link seem not pre-trained models. The model of charades dataset has low mAP, could you reload the correct model?
thanks!

**Comment by yytzsy** [comment]
Hi, I have checked the pre-traind models and got reasonable results. The uploaded files are right, and maybe you should check your running.

**Comment by TianyuLee** [comment]
OK, thanks！

**Comment by chenxhhh** [comment]
I also encountered this problem, so I trained the model myself and achieved similar results with the results in the paper.
