### ISSUE TITLE
I3D extractor

### ISSUE THREAD

**Issue by Tanwey** [yytzsy/SCDM#3]
Hi Yitian,
 
I need to more precise I3D features(higher fps).Could you please share the codes for I3D extractor?
Thanks

**Comment by TianyuLee** [comment]
I have a similar question: Are the I3D features and C3D features fine-tuned in (charades,activitynet) dataset? or  just trained in (sports-1m , kinetics) dataset?
thanks!

**Comment by yytzsy** [comment]
We do not finetune the feature extraction network in any other datasets, and just use the pretrained model on sports-1m to get the video features. For C3D feature extraction, we follow https://github.com/yyuanad/Pytorch_C3D_Feature_Extractor, and for I3D feature extraction, please refer https://github.com/JaywongWang/I3D-Feature-Extractor

**Comment by TianyuLee** [comment]
OK, thank you and your code very much!

**Comment by Tanwey** [comment]
Thanks for your sharing!

**Comment by Sy-Zhang** [comment]
For I3D extraction of Charades, I got same result with the "rgb600" checkpoint (pretrained on Kinetics 600) instead of the default "rgb_imagenet" checkpoint (pretrained on Kinetics 400). Also, All videos are decoded at 16 fps.
