### ISSUE TITLE
can't download preextracted activityNet feature

### ISSUE THREAD

**Issue by yangwf1** [yytzsy/SCDM#5]
when i try to download the activityNet feature, it shows that request is refused, is it dut to that the data is not publically avaliable?

**Comment by yytzsy** [comment]
Do you mean the 'activitynet_c3d_fc6_stride_1s.hdf5' feature？ I have checked it and it can be downloaded.

**Comment by jessiSYJ** [comment]
I have met the same problem as yours, then I realized I forgot to open the vpn. You may have made the same mistake as mine.

**Comment by yytzsy** [comment]
The video features are available.
