### ISSUE TITLE
cannot download the extracted video features

### ISSUE THREAD

**Issue by forkarinda** [yytzsy/SCDM#6]
Hello, when I tried to download the video feature of Google Drive provided by you, it prompted that the download requires access permission. Can you fix the downloading of video features, I would be very grateful!

**Comment by yytzsy** [comment]
Sorry for the disable of the video features, there is something wrong with my google drive. I will fix it soon.

**Comment by forkarinda** [comment]
Thanks for your help!

**Comment by forkarinda** [comment]
Hello,  I try to download the provided video feature again, but it still prompted that the download requires access permission. Is there any other solution? I would be very grateful!

**Comment by yangwf1** [comment]
I meet the same issue,it would be very grateful to fix the download issue

**Comment by yytzsy** [comment]
Hello, sorry for my late reply. The video features are available now.

**Comment by yytzsy** [comment]
The video features are available now.
